import WordCloud from "./components/wordcloud"

export default function App() {
  const data = [
    { text: "happy", value: 8, sentiment: "positive" },
    { text: "joyful", value: 6, sentiment: "positive" },
    { text: "exciting", value: 7, sentiment: "positive" },
    { text: "awesome", value: 9, sentiment: "positive" },
    { text: "fantastic", value: 8, sentiment: "positive" },
    { text: "amazing", value: 9, sentiment: "positive" },
    { text: "wonderful", value: 7, sentiment: "positive" },
    { text: "positive", value: 20, sentiment: "positive" },
    { text: "good", value: 8, sentiment: "positive" },
    { text: "excellent", value: 9, sentiment: "positive" },
    { text: "sad", value: 3, sentiment: "negative" },
    { text: "angry", value: 4, sentiment: "negative" },
    { text: "disappointed", value: 5, sentiment: "negative" },
    { text: "horrible", value: 2, sentiment: "negative" },
    { text: "terrible", value: 2, sentiment: "negative" },
    { text: "frustrating", value: 3, sentiment: "negative" },
    { text: "awful", value: 2, sentiment: "negative" },
    { text: "unpleasant", value: 3, sentiment: "negative" },
    { text: "boring", value: 4, sentiment: "negative" },
    { text: "ordinary", value: 5, sentiment: "negative" },
    { text: "satisfied", value: 7, sentiment: "positive" },
    { text: "pleasing", value: 8, sentiment: "positive" },
    { text: "delightful", value: 9, sentiment: "positive" },
    { text: "cheerful", value: 8, sentiment: "positive" },
    { text: "exuberant", value: 9, sentiment: "positive" },
    { text: "grateful", value: 8, sentiment: "positive" },
    { text: "uplifting", value: 7, sentiment: "positive" },
    { text: "hopeful", value: 8, sentiment: "positive" },
    { text: "inspiring", value: 9, sentiment: "positive" },
    { text: "dismal", value: 3, sentiment: "negative" },
    { text: "gloomy", value: 4, sentiment: "negative" },
    { text: "dreary", value: 2, sentiment: "negative" },
    { text: "miserable", value: 2, sentiment: "negative" },
    { text: "unfortunate", value: 3, sentiment: "negative" },
    { text: "blissful", value: 9, sentiment: "positive" },
    { text: "radiant", value: 8, sentiment: "positive" },
    { text: "pleasurable", value: 7, sentiment: "positive" },
    { text: "exhilarating", value: 9, sentiment: "positive" },
    { text: "magnificent", value: 10, sentiment: "positive" },
    { text: "euphoric", value: 9, sentiment: "positive" },
    { text: "jubilant", value: 8, sentiment: "positive" },
    { text: "upbeat", value: 7, sentiment: "positive" },
    { text: "sunny", value: 8, sentiment: "positive" },
    { text: "heartwarming", value: 7, sentiment: "positive" },
    { text: "content", value: 8, sentiment: "positive" },
    { text: "satisfying", value: 9, sentiment: "positive" },
    { text: "fulfilling", value: 8, sentiment: "positive" },
    { text: "amused", value: 7, sentiment: "positive" },
    { text: "jovial", value: 8, sentiment: "positive" },
    { text: "festive", value: 9, sentiment: "positive" },
    { text: "optimistic", value: 8, sentiment: "positive" },
    { text: "vibrant", value: 9, sentiment: "positive" },
    { text: "playful", value: 7, sentiment: "positive" },
    { text: "contented", value: 8, sentiment: "positive" },
    { text: "thrilled", value: 9, sentiment: "positive" },
    { text: "gratified", value: 8, sentiment: "positive" },
    { text: "overjoyed", value: 10, sentiment: "positive" },
    { text: "serene", value: 8, sentiment: "positive" },
    { text: "tranquil", value: 7, sentiment: "positive" },
    { text: "ecstatic", value: 9, sentiment: "positive" },
    { text: "exultant", value: 9, sentiment: "positive" },
  ]
  return (
    <WordCloud
      options={{
        words: data,
        verticalEnabled: true,
        minFont: 10,
        maxFont: 50,
        fontOffset: 0.9,
        width: 390,
        height: 844,
        fontFamily: "",
      }}
    />
  )
}
